import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1774819681025 implements MigrationInterface {
    name = 'InitialSchema1774819681025'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."sla_policies_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TABLE "sla_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "priority" "public"."sla_policies_priority_enum" NOT NULL, "responseTimeMinutes" integer NOT NULL, "resolutionTimeMinutes" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "escalateOnBreach" boolean NOT NULL DEFAULT false, "escalationRules" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_41b6803cef982534243a67b6302" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "authorId" uuid NOT NULL, "content" text NOT NULL, "attachments" jsonb, "isInternal" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_811ed3b81dd8df6b9a92058d89c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ticket_history_action_enum" AS ENUM('created', 'status_changed', 'priority_changed', 'assigned', 'reassigned', 'unassigned', 'comment_added', 'sla_set', 'sla_breached', 'escalated', 'resolved', 'closed', 'reopened', 'custom_field_changed')`);
        await queryRunner.query(`CREATE TABLE "ticket_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "changedById" uuid, "action" "public"."ticket_history_action_enum" NOT NULL, "oldValue" jsonb, "newValue" jsonb, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6d0f4bc32cc3581d6a016bca30a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ticket_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "uploadedById" uuid NOT NULL, "filename" character varying NOT NULL, "fileUrl" character varying NOT NULL, "fileSize" integer NOT NULL, "mimeType" character varying, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e5011f87f95e78fe4bd7d982a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."escalations_level_enum" AS ENUM('level_1', 'level_2', 'level_3', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."escalations_status_enum" AS ENUM('pending', 'in_progress', 'resolved', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "escalations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "organizationId" uuid NOT NULL, "level" "public"."escalations_level_enum" NOT NULL, "status" "public"."escalations_status_enum" NOT NULL DEFAULT 'pending', "escalatedToId" uuid, "reason" text, "escalatedAt" TIMESTAMP NOT NULL, "resolvedAt" TIMESTAMP, "notificationsSent" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_652a394609addaa4b0f2b3032a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."locations_type_enum" AS ENUM('office', 'warehouse', 'service_area', 'customer_site', 'other')`);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "type" "public"."locations_type_enum" NOT NULL, "address" character varying NOT NULL, "city" character varying, "state" character varying, "postalCode" character varying, "country" character varying, "latitude" numeric(10,8), "longitude" numeric(11,8), "serviceRadius" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."customers_status_enum" AS ENUM('active', 'inactive', 'blocked', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "description" text, "organizationId" uuid NOT NULL, "status" "public"."customers_status_enum" NOT NULL DEFAULT 'active', "address" character varying, "city" character varying, "country" character varying, "customFields" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "service_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "estimatedDurationMinutes" integer NOT NULL DEFAULT '0', "baseCost" numeric(10,2), "requiredSkills" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1dc93417a097cdee3491f39d7cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_priority_enum" AS ENUM('low', 'medium', 'high', 'urgent')`);
        await queryRunner.query(`CREATE TYPE "public"."tickets_status_enum" AS ENUM('pending', 'in_queue', 'assigned', 'in_progress', 'on_hold', 'resolved', 'closed')`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "priority" "public"."tickets_priority_enum" NOT NULL DEFAULT 'medium', "status" "public"."tickets_status_enum" NOT NULL DEFAULT 'pending', "organizationId" uuid NOT NULL, "createdById" uuid, "slaPolicyId" uuid, "slaDeadline" TIMESTAMP, "slaBreached" boolean NOT NULL DEFAULT false, "locationId" uuid, "customerId" uuid, "serviceTypeId" uuid, "customFields" jsonb, "requiredSkills" jsonb, "estimatedDurationMinutes" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP, "closedAt" TIMESTAMP, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."assignments_status_enum" AS ENUM('pending', 'accepted', 'declined', 'in_progress', 'completed')`);
        await queryRunner.query(`CREATE TABLE "assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticketId" uuid NOT NULL, "agentId" uuid NOT NULL, "status" "public"."assignments_status_enum" NOT NULL DEFAULT 'pending', "isAutoAssigned" boolean NOT NULL DEFAULT false, "notes" text, "acceptedAt" TIMESTAMP, "startedAt" TIMESTAMP, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_cc9ed03c1ca2d53774480c0468" UNIQUE ("ticketId"), CONSTRAINT "PK_c54ca359535e0012b04dcbd80ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('assignment', 'sla_warning', 'sla_breach', 'escalation', 'comment', 'status_change', 'system')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipientId" uuid NOT NULL, "organizationId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "channels" text NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "metadata" jsonb, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP, "relatedEntityId" uuid, "relatedEntityType" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'manager', 'dispatcher', 'agent')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "phone" character varying, "organizationId" uuid NOT NULL, "skills" jsonb, "currentLoad" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "skills" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('draft', 'sent', 'paid', 'overdue', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceNumber" character varying NOT NULL, "organizationId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'draft', "issueDate" date NOT NULL, "dueDate" date NOT NULL, "paidDate" date, "description" text, "lineItems" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bf8e0f9dd4558ef209ec111782d" UNIQUE ("invoiceNumber"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "categoryId" uuid NOT NULL, "organizationId" uuid NOT NULL, "proficiencyLevel" integer NOT NULL DEFAULT '1', "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "skill_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "priority" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_efce364bf7be7b92b7d7f948663" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_type_enum" AS ENUM('webhook', 'api', 'email', 'telegram', 'slack', 'zapier', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."integrations_status_enum" AS ENUM('active', 'inactive', 'error', 'pending')`);
        await queryRunner.query(`CREATE TABLE "integrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."integrations_type_enum" NOT NULL, "organizationId" uuid NOT NULL, "status" "public"."integrations_status_enum" NOT NULL DEFAULT 'pending', "description" text, "config" jsonb NOT NULL, "credentials" jsonb, "metadata" jsonb, "lastSyncAt" TIMESTAMP, "lastErrorAt" TIMESTAMP, "lastError" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9adcdc6d6f3922535361ce641e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_items_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'retrying', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "queue_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "queueId" uuid NOT NULL, "ticketId" uuid, "status" "public"."queue_items_status_enum" NOT NULL DEFAULT 'pending', "priority" integer NOT NULL DEFAULT '0', "retryCount" integer NOT NULL DEFAULT '0', "processedAt" TIMESTAMP, "completedAt" TIMESTAMP, "errorMessage" text, "payload" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2245e11ac3517494bacfe932773" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queues_strategy_enum" AS ENUM('fifo', 'priority', 'load_balanced', 'skill_based', 'round_robin')`);
        await queryRunner.query(`CREATE TABLE "queues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "strategy" "public"."queues_strategy_enum" NOT NULL DEFAULT 'load_balanced', "itemCount" integer NOT NULL DEFAULT '0', "processingCount" integer NOT NULL DEFAULT '0', "completedCount" integer NOT NULL DEFAULT '0', "rules" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d966f9eb39a9396658387071bb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_plans_type_enum" AS ENUM('starter', 'professional', 'enterprise', 'custom')`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."subscription_plans_type_enum" NOT NULL, "description" text, "monthlyPrice" numeric(10,2) NOT NULL, "annualPrice" numeric(10,2), "maxUsers" integer NOT NULL, "maxTicketsPerMonth" integer NOT NULL, "maxTeams" integer, "features" jsonb NOT NULL, "limits" jsonb, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9ab8fe6918451ab3d0a4fb6bb0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('active', 'paused', 'cancelled', 'expired', 'trial')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "planId" uuid NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'trial', "startDate" date NOT NULL, "endDate" date NOT NULL, "renewalDate" date, "monthlyPrice" numeric(12,2) NOT NULL, "userCount" integer NOT NULL DEFAULT '1', "ticketsProcessed" integer NOT NULL DEFAULT '0', "autoRenew" boolean NOT NULL DEFAULT true, "features" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_resource_enum" AS ENUM('tickets', 'assignments', 'users', 'teams', 'organizations', 'reports', 'settings', 'integrations', 'sla', 'queues', 'analytics')`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('create', 'read', 'update', 'delete', 'execute')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" "public"."permissions_resource_enum" NOT NULL, "action" "public"."permissions_action_enum" NOT NULL, "description" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "roleId" uuid NOT NULL, "organizationId" uuid NOT NULL, "validFrom" date, "validUntil" date, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc2df9835ac1d2a34839f113783" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "organizationId" uuid NOT NULL, "isSystem" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('create', 'update', 'delete', 'read', 'login', 'logout', 'export', 'import', 'permission_change', 'settings_change')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "actorId" uuid, "action" "public"."audit_logs_action_enum" NOT NULL, "entityType" character varying NOT NULL, "entityId" character varying NOT NULL, "changes" jsonb, "metadata" jsonb, "ipAddress" character varying, "userAgent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."metrics_type_enum" AS ENUM('sla_compliance', 'agent_performance', 'queue_length', 'average_resolution_time', 'customer_satisfaction', 'ticket_volume', 'response_time', 'escalation_rate')`);
        await queryRunner.query(`CREATE TABLE "metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organizationId" uuid NOT NULL, "type" "public"."metrics_type_enum" NOT NULL, "value" numeric(10,2) NOT NULL, "unit" character varying, "date" date NOT NULL, "dimensions" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5283cad666a83376e28a715bf0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_type_enum" AS ENUM('sla_compliance', 'agent_performance', 'queue_analysis', 'financial', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('pending', 'generating', 'ready', 'failed')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."reports_type_enum" NOT NULL, "organizationId" uuid NOT NULL, "createdById" uuid NOT NULL, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'pending', "startDate" date NOT NULL, "endDate" date NOT NULL, "filters" jsonb, "data" jsonb, "fileUrl" character varying, "errorMessage" text, "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "settings" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9b7ca6d30b94fef571cff876884" UNIQUE ("name"), CONSTRAINT "UQ_963693341bd612aa01ddf3a4b68" UNIQUE ("slug"), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."webhook_events_status_enum" AS ENUM('pending', 'delivered', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "webhook_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "webhookId" uuid NOT NULL, "eventType" character varying NOT NULL, "payload" jsonb NOT NULL, "status" "public"."webhook_events_status_enum" NOT NULL DEFAULT 'pending', "attemptCount" integer NOT NULL DEFAULT '0', "httpStatusCode" integer, "responseBody" text, "deliveredAt" TIMESTAMP, "nextRetryAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4cba37e6a0acb5e1fc49c34ebfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "organizationId" uuid NOT NULL, "url" character varying NOT NULL, "events" text NOT NULL, "headers" jsonb, "metadata" jsonb, "isActive" boolean NOT NULL DEFAULT true, "failureCount" integer NOT NULL DEFAULT '0', "lastDeliveredAt" TIMESTAMP, "lastFailedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9e8795cfc899ab7bdaa831e8527" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "team_members" ("team_id" uuid NOT NULL, "user_id" uuid NOT NULL, CONSTRAINT "PK_1d3c06a8217a8785e2af0ec4ab8" PRIMARY KEY ("team_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fdad7d5768277e60c40e01cdce" ON "team_members" ("team_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2bf4967c8c2a6b845dadfbf3d" ON "team_members" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "sla_policies" ADD CONSTRAINT "FK_8180674b393d8734a0b1fd07924" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_comments" ADD CONSTRAINT "FK_f6beba8ae36e1ce20968d7a3192" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_comments" ADD CONSTRAINT "FK_4497112178bae33622ee27543e4" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_history" ADD CONSTRAINT "FK_2bde375c7f9f2ffd77381df611b" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_history" ADD CONSTRAINT "FK_392d4316da8dc2e1bb3b72cc850" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_attachments" ADD CONSTRAINT "FK_56b2e0448dbbd5e8d50c96fe910" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ticket_attachments" ADD CONSTRAINT "FK_13333dac9f7f411707ea6236c7a" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escalations" ADD CONSTRAINT "FK_ee8ea4820ff086b48ddbbb3afdc" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escalations" ADD CONSTRAINT "FK_b7ac5f9ae84473ef1c5dd9e4d51" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escalations" ADD CONSTRAINT "FK_b015dac43051b24c04525b97460" FOREIGN KEY ("escalatedToId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "locations" ADD CONSTRAINT "FK_6ccf3c1c271638b4782216853a9" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_fac3145c49520eae6248715b26b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_types" ADD CONSTRAINT "FK_25b5807d12d1ea10f549613b10b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_98f00985a13412ab11f4d1c1000" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_41de538b3eed286f53dd678b030" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_92956078210b77b3704fc5befc4" FOREIGN KEY ("slaPolicyId") REFERENCES "sla_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_7abac3d1c71638288916909d357" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_7a1f978a1c1a6b2b1133014b4b2" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tickets" ADD CONSTRAINT "FK_46ba2e4e917962b6211cd78f25c" FOREIGN KEY ("serviceTypeId") REFERENCES "service_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_cc9ed03c1ca2d53774480c04683" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assignments" ADD CONSTRAINT "FK_29d76e75c370b79104de29560c7" FOREIGN KEY ("agentId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_928914a0743f50e6f83a90cdda9" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_858389ddeb0bd6c6bf4e323f91e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_4237f4b816fec1df81bd85f833f" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_06d267f85858229c10a01a08ad7" FOREIGN KEY ("categoryId") REFERENCES "skill_categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_c8e84d8dab61c6ab97f9366df8a" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skill_categories" ADD CONSTRAINT "FK_d67887282ce25656ef127fd965d" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integrations" ADD CONSTRAINT "FK_3414ce986a725cc9435da921c6d" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_items" ADD CONSTRAINT "FK_b487775b90610d8e94584d25903" FOREIGN KEY ("queueId") REFERENCES "queues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_items" ADD CONSTRAINT "FK_dfd0e7b7285cfec5b6a15a82025" FOREIGN KEY ("ticketId") REFERENCES "tickets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queues" ADD CONSTRAINT "FK_5584e2245e90b4144c6cb97925b" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_a7a84c705f3e8e4fbd497cfb119" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7536cba909dd7584a4640cad7d5" FOREIGN KEY ("planId") REFERENCES "subscription_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_assignments" ADD CONSTRAINT "FK_4c31464b76da5895e211a5d2099" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_assignments" ADD CONSTRAINT "FK_6000ca1e3e8add1eb504f139a7b" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_assignments" ADD CONSTRAINT "FK_34145a773ccfe37d799d1f6c4de" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_0933e1dfb2993d672af1a98f08e" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2d031e6155834882f54dcd6b4f5" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metrics" ADD CONSTRAINT "FK_df883445d3147a0d58c948bbd20" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_2a7f46c9ab476059a4c86d05f78" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_fddee96a7e01bddcc3e5eb610bf" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhook_events" ADD CONSTRAINT "FK_7c857d21e12e81fd6ce8585d057" FOREIGN KEY ("webhookId") REFERENCES "webhooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "webhooks" ADD CONSTRAINT "FK_dbecd97048eef1ff16f24a01313" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_fdad7d5768277e60c40e01cdcea" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "team_members" ADD CONSTRAINT "FK_c2bf4967c8c2a6b845dadfbf3d4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_c2bf4967c8c2a6b845dadfbf3d4"`);
        await queryRunner.query(`ALTER TABLE "team_members" DROP CONSTRAINT "FK_fdad7d5768277e60c40e01cdcea"`);
        await queryRunner.query(`ALTER TABLE "webhooks" DROP CONSTRAINT "FK_dbecd97048eef1ff16f24a01313"`);
        await queryRunner.query(`ALTER TABLE "webhook_events" DROP CONSTRAINT "FK_7c857d21e12e81fd6ce8585d057"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_fddee96a7e01bddcc3e5eb610bf"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_2a7f46c9ab476059a4c86d05f78"`);
        await queryRunner.query(`ALTER TABLE "metrics" DROP CONSTRAINT "FK_df883445d3147a0d58c948bbd20"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2d031e6155834882f54dcd6b4f5"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_0933e1dfb2993d672af1a98f08e"`);
        await queryRunner.query(`ALTER TABLE "role_assignments" DROP CONSTRAINT "FK_34145a773ccfe37d799d1f6c4de"`);
        await queryRunner.query(`ALTER TABLE "role_assignments" DROP CONSTRAINT "FK_6000ca1e3e8add1eb504f139a7b"`);
        await queryRunner.query(`ALTER TABLE "role_assignments" DROP CONSTRAINT "FK_4c31464b76da5895e211a5d2099"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7536cba909dd7584a4640cad7d5"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_a7a84c705f3e8e4fbd497cfb119"`);
        await queryRunner.query(`ALTER TABLE "queues" DROP CONSTRAINT "FK_5584e2245e90b4144c6cb97925b"`);
        await queryRunner.query(`ALTER TABLE "queue_items" DROP CONSTRAINT "FK_dfd0e7b7285cfec5b6a15a82025"`);
        await queryRunner.query(`ALTER TABLE "queue_items" DROP CONSTRAINT "FK_b487775b90610d8e94584d25903"`);
        await queryRunner.query(`ALTER TABLE "integrations" DROP CONSTRAINT "FK_3414ce986a725cc9435da921c6d"`);
        await queryRunner.query(`ALTER TABLE "skill_categories" DROP CONSTRAINT "FK_d67887282ce25656ef127fd965d"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_c8e84d8dab61c6ab97f9366df8a"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_06d267f85858229c10a01a08ad7"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_4237f4b816fec1df81bd85f833f"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_858389ddeb0bd6c6bf4e323f91e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f3d6aea8fcca58182b2e80ce979"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_928914a0743f50e6f83a90cdda9"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_29d76e75c370b79104de29560c7"`);
        await queryRunner.query(`ALTER TABLE "assignments" DROP CONSTRAINT "FK_cc9ed03c1ca2d53774480c04683"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_46ba2e4e917962b6211cd78f25c"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_7a1f978a1c1a6b2b1133014b4b2"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_7abac3d1c71638288916909d357"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_92956078210b77b3704fc5befc4"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_41de538b3eed286f53dd678b030"`);
        await queryRunner.query(`ALTER TABLE "tickets" DROP CONSTRAINT "FK_98f00985a13412ab11f4d1c1000"`);
        await queryRunner.query(`ALTER TABLE "service_types" DROP CONSTRAINT "FK_25b5807d12d1ea10f549613b10b"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_fac3145c49520eae6248715b26b"`);
        await queryRunner.query(`ALTER TABLE "locations" DROP CONSTRAINT "FK_6ccf3c1c271638b4782216853a9"`);
        await queryRunner.query(`ALTER TABLE "escalations" DROP CONSTRAINT "FK_b015dac43051b24c04525b97460"`);
        await queryRunner.query(`ALTER TABLE "escalations" DROP CONSTRAINT "FK_b7ac5f9ae84473ef1c5dd9e4d51"`);
        await queryRunner.query(`ALTER TABLE "escalations" DROP CONSTRAINT "FK_ee8ea4820ff086b48ddbbb3afdc"`);
        await queryRunner.query(`ALTER TABLE "ticket_attachments" DROP CONSTRAINT "FK_13333dac9f7f411707ea6236c7a"`);
        await queryRunner.query(`ALTER TABLE "ticket_attachments" DROP CONSTRAINT "FK_56b2e0448dbbd5e8d50c96fe910"`);
        await queryRunner.query(`ALTER TABLE "ticket_history" DROP CONSTRAINT "FK_392d4316da8dc2e1bb3b72cc850"`);
        await queryRunner.query(`ALTER TABLE "ticket_history" DROP CONSTRAINT "FK_2bde375c7f9f2ffd77381df611b"`);
        await queryRunner.query(`ALTER TABLE "ticket_comments" DROP CONSTRAINT "FK_4497112178bae33622ee27543e4"`);
        await queryRunner.query(`ALTER TABLE "ticket_comments" DROP CONSTRAINT "FK_f6beba8ae36e1ce20968d7a3192"`);
        await queryRunner.query(`ALTER TABLE "sla_policies" DROP CONSTRAINT "FK_8180674b393d8734a0b1fd07924"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2bf4967c8c2a6b845dadfbf3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fdad7d5768277e60c40e01cdce"`);
        await queryRunner.query(`DROP TABLE "team_members"`);
        await queryRunner.query(`DROP TABLE "webhooks"`);
        await queryRunner.query(`DROP TABLE "webhook_events"`);
        await queryRunner.query(`DROP TYPE "public"."webhook_events_status_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_type_enum"`);
        await queryRunner.query(`DROP TABLE "metrics"`);
        await queryRunner.query(`DROP TYPE "public"."metrics_type_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_assignments"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_resource_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_plans_type_enum"`);
        await queryRunner.query(`DROP TABLE "queues"`);
        await queryRunner.query(`DROP TYPE "public"."queues_strategy_enum"`);
        await queryRunner.query(`DROP TABLE "queue_items"`);
        await queryRunner.query(`DROP TYPE "public"."queue_items_status_enum"`);
        await queryRunner.query(`DROP TABLE "integrations"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."integrations_type_enum"`);
        await queryRunner.query(`DROP TABLE "skill_categories"`);
        await queryRunner.query(`DROP TABLE "skills"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "assignments"`);
        await queryRunner.query(`DROP TYPE "public"."assignments_status_enum"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tickets_priority_enum"`);
        await queryRunner.query(`DROP TABLE "service_types"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_status_enum"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP TYPE "public"."locations_type_enum"`);
        await queryRunner.query(`DROP TABLE "escalations"`);
        await queryRunner.query(`DROP TYPE "public"."escalations_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."escalations_level_enum"`);
        await queryRunner.query(`DROP TABLE "ticket_attachments"`);
        await queryRunner.query(`DROP TABLE "ticket_history"`);
        await queryRunner.query(`DROP TYPE "public"."ticket_history_action_enum"`);
        await queryRunner.query(`DROP TABLE "ticket_comments"`);
        await queryRunner.query(`DROP TABLE "sla_policies"`);
        await queryRunner.query(`DROP TYPE "public"."sla_policies_priority_enum"`);
    }

}
